name: Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        cmakeflags:
        -
        - -DCMAKE_BUILD_TYPE=Release -DTTLS_ASAN=ON
        - -DTTLS_OPENSSL=ON
        - -DCMAKE_BUILD_TYPE=Release -DTTLS_ASAN=ON -DTTLS_OPENSSL=ON
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup
        run: |
          sudo apt update
          sudo apt install clang-tidy-11 libmbedtls-dev
          mkdir build

      - name: Build
        run: |
          cmake ${{ matrix.cmakeflags }} ..
          make -j`nproc`
        working-directory: build

      - name: Test
        run: ctest --output-on-failure
        working-directory: build
